export { default as Spinner } from './Spinner'
export { default as Error } from './Error'
export { default as Footer } from './Footer'
export { default as SearchBox } from './SearchBox'
export { default as MemesDisplay } from './MemesDisplay'
